version: '3.8'

services:
  # Serviço do MySQL
  db: 
    image: mysql:8.0
    environment:
      # senha do usuario root
      MYSQL_ROOT_PASSWORD: root
      # nome do banco
      MYSQL_DATABASE: adaptride
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # Serviço do Backend
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3001"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: adaptride
    depends_on:
      - db
    networks:
      - app-network

  # Serviço do Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

# Volumes
volumes:
  db_data:  

# Networks
networks:
  app-network:

